### Variables
@apiurl = http://localhost:4001

### User routes

### Post User (Create a new user)
## this comeback a token

POST {{apiurl}}/user/singup
Content-Type: application/json

{
    "username":"otário",
    "email":"otr@gmail.om",
    "password":"admin123"
}

## Response: token: {kajsçkfajskdfja...}

### Post login (login in user account)
## this comeback a token too
POST {{apiurl}}/user/login
Content-Type: application/json

{
    "email":"otr@gmail.om",
    "password":"admin123"
}

### Post get user informations
## this comeback all user informations

GET {{apiurl}}/user/informations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hY2Vkb0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwOCRQQXpRMjQ2T3dkeks1Y3YyQi5mOWxPc29ka09qVjdsd25tNEN0T0xQMmNxMlliZFNUSHE4MiIsImlhdCI6MTczNDg4NzA3NiwiZXhwIjoxNzM1NDkxODc2fQ.PeXnkDm9xI4lmizb552sWxkTzfx6aLvjQa4CPhJYI1k
### The response is something like this:
# {
#   "user": {
#     "id": 4,
#     "username": "otário",
#     "email": "otr@gmail.om",
#     "password": "$2a$08$uSnJq9VtGnPBorSR7b5DoO6ALz8H6t0ZdFXjgaR4JGhrTN.LtRVSG"
#   }
# }

### POST favorite (endpoint for create a new favorite movie)

POST {{apiurl}}/favorite/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hY2Vkb0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQwOCRQQXpRMjQ2T3dkeks1Y3YyQi5mOWxPc29ka09qVjdsd25tNEN0T0xQMmNxMlliZFNUSHE4MiIsImlhdCI6MTczNDg4NzA3NiwiZXhwIjoxNzM1NDkxODc2fQ.PeXnkDm9xI4lmizb552sWxkTzfx6aLvjQa4CPhJYI1k

{
    "movieId": 225
}

### This response is something like this
# {
#   "message": "movie favorited",
#   "favorite": 220
# }